//---------------------------------------------------------------------------
// TestHarvest.cpp
//---------------------------------------------------------------------------
#include "TestHarvest.h"
#include <gtest/gtest.h>
#include <fstream>
#include <math.h>
#include <sstream>


/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile1()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile1(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Paper_Birch\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>clear</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_maxSnagDecayClass>-1</ha_maxSnagDecayClass>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100.0</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_maxSnagDecayClass>-1</ha_maxSnagDecayClass>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>30.0</ha_high>"
      << "<ha_amountToCut>0.2</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>40.0</ha_low>"
      << "<ha_high>80.0</ha_high>"
      << "<ha_amountToCut>0.2</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_maxSnagDecayClass>-1</ha_maxSnagDecayClass>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>300.0</ha_high>"
      << "<ha_amountToCut>35</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Amabilis_Fir\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Hemlock\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">0</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile2()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile2()
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 2);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_maxSnagDecayClass>1</ha_maxSnagDecayClass>"
      << "<ha_dbhRange>"
      << "<ha_low>15.0</ha_low>"
      << "<ha_high>45.0</ha_high>"
      << "<ha_amountToCut>50.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>50.0</ha_low>"
      << "<ha_high>80.0</ha_high>"
      << "<ha_amountToCut>40.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>80.0</ha_low>"
      << "<ha_high>85.0</ha_high>"
      << "<ha_amountToCut>30.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>90.0</ha_low>"
      << "<ha_high>99.0</ha_high>"
      << "<ha_amountToCut>20.0</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile3()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile3(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<listPosition>1</listPosition>"
      << "<version>1</version>"
      << "</behavior>"
      //To allow snags to exist
      << "<behavior>"
      << "<behaviorName>ConstantGLI</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>2</listPosition>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Snag\"/>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Trembling_Aspen\" />"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_maxSnagDecayClass>1</ha_maxSnagDecayClass>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>15.0</ha_low>"
      << "<ha_high>45.0</ha_high>"
      << "<ha_amountToCut>1</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>50.0</ha_low>"
      << "<ha_high>80.0</ha_high>"
      << "<ha_amountToCut>1</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>80.0</ha_low>"
      << "<ha_high>85.0</ha_high>"
      << "<ha_amountToCut>1</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>90.0</ha_low>"
      << "<ha_high>100.0</ha_high>"
      << "<ha_amountToCut>1</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "<ConstantGLI2>"
      << "<li_constGLI>100</li_constGLI>"
      << "</ConstantGLI2>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile4()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile4(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";
  int i;

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_timestep>2</ha_timestep>"
      << "<ha_cutType>gap</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Western_Hemlock\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Amabilis_Fir\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">50</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">0</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_timestep>2</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>15.0</ha_low>"
      << "<ha_high>45.0</ha_high>"
      << "<ha_amountToCut>50</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>50.0</ha_low>"
      << "<ha_high>80.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>80.0</ha_low>"
      << "<ha_high>85.0</ha_high>"
      << "<ha_amountToCut>30</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>90.0</ha_low>"
      << "<ha_high>100.0</ha_high>"
      << "<ha_amountToCut>0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Western_Hemlock\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Amabilis_Fir\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">0</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  for (int i = 0; i < 6; i++) {
    for (int j = 0; j < 10; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>10.0</ha_high>"
      << "<ha_amountToCut>50</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>10.0</ha_low>"
      << "<ha_high>20.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>20.0</ha_low>"
      << "<ha_high>30.0</ha_high>"
      << "<ha_amountToCut>30</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>30.0</ha_low>"
      << "<ha_high>40.0</ha_high>"
      << "<ha_amountToCut>0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Amabilis_Fir\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Hemlock\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">0</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">25</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  for (int i = 0; i < 6; i++) {
    for (int j = 0; j < 10; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>200.0</ha_low>"
      << "<ha_high>300.0</ha_high>"
      << "<ha_amountToCut>50</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>50.0</ha_low>"
      << "<ha_high>80.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>80.0</ha_low>"
      << "<ha_high>85.0</ha_high>"
      << "<ha_amountToCut>30</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>90.0</ha_low>"
      << "<ha_high>100.0</ha_high>"
      << "<ha_amountToCut>0</ha_amountToCut>"
      << "</ha_dbhRange>";
  i = 6;
  for (int j = 6; j < 25; j++) {
    oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
  }
  i = 8;
  for (int j = 6; j < 25; j++) {
    oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile5()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile5(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";
  int i, j;

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_applyToSpecies species=\"Subalpine_Fir\" />"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_applyToSpecies species=\"Trembling_Aspen\" />"
      << "<ha_applyToSpecies species=\"Paper_Birch\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>10.0</ha_high>"
      << "<ha_amountToCut>5.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>10.0</ha_low>"
      << "<ha_high>20.0</ha_high>"
      << "<ha_amountToCut>100.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>20.0</ha_low>"
      << "<ha_high>30.0</ha_high>"
      << "<ha_amountToCut>3.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_dbhRange>"
      << "<ha_low>30.0</ha_low>"
      << "<ha_high>40.0</ha_high>"
      << "<ha_amountToCut>0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Western_Hemlock\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Amabilis_Fir\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">100</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  i = 6;
  for (int j = 6; j < 25; j++) {
    oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
  }
  for (i = 8; i < 25; i++) {
    for (j = 0; j < 13; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile6()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile6(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";
  int i;

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Subalpine_Fir\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>clear</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100.0</ha_amountToCut>"
      << "</ha_dbhRange>";
  i = 6;
  for (int j = 6; j < 25; j++) {
    oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
  }
  i = 8;
  for (int j = 6; j < 25; j++) {
    oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_timestep>2</ha_timestep>"
      << "<ha_cutType>gap</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>30.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 6; i++) {
    for (int j = 0; j < 10; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_timestep>2</ha_timestep>"
      << "<ha_cutType>gap</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 6; i++) {
    for (int j = 0; j < 10; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>300.0</ha_high>"
      << "<ha_amountToCut>50</ha_amountToCut>"
      << "</ha_dbhRange>";
  oOut << "<ha_applyToCell x=\"" << 0 << "\" y=\"" << 10 << "\" /> ";
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>300.0</ha_high>"
      << "<ha_amountToCut>4.5</ha_amountToCut>"
      << "</ha_dbhRange>";
  oOut << "<ha_applyToCell x=\"" << 5 << "\" y=\"" << 5 << "\" /> ";
  /*  oOut << "</ha_cutEvent>"
       << "<ha_cutEvent>"
       << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
       << "<ha_timestep>3</ha_timestep>"
       << "<ha_cutType>partial</ha_cutType>"
       << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
       << "<ha_dbhRange>"
       << "<ha_low>0.0</ha_low>"
       << "<ha_high>300.0</ha_high>"
       << "<ha_amountToCut>50</ha_amountToCut>"
       << "</ha_dbhRange>"; */
  oOut << "<ha_applyToCell x=\"" << 10 << "\" y=\"" << 23 << "\" /> ";
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>300.0</ha_high>"
      << "<ha_amountToCut>312.5</ha_amountToCut>"
      << "</ha_dbhRange>";
  oOut << "<ha_applyToCell x=\"" << 1 << "\" y=\"" << 1 << "\" /> ";
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Trembling_Aspen\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>clear</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>";
  oOut << "<ha_applyToCell x=\"" << 20 << "\" y=\"" << 0 << "\" /> ";
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_timestep>3</ha_timestep>"
      << "<ha_cutType>gap</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100</ha_amountToCut>"
      << "</ha_dbhRange>";
  oOut << "<ha_applyToCell x=\"" << 1 << "\" y=\"" << 7 << "\" /> ";
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}


/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile8()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile8()
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  WriteHarvestFileBeginning(oOut, 1);

  oOut << "<grid gridName=\"harvestmastercuts\">"
      << "<ma_lengthXCells>2</ma_lengthXCells>"
      << "<ma_lengthYCells>2</ma_lengthYCells>"
      << "</grid>"
      << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>2</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>ConstantGLI</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>2</listPosition>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Snag\"/>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>StochasticMortality</behaviorName>"
      << "<version>1</version>"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Adult\" />"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Snag\" />"
      << "<applyTo species=\"Paper_Birch\" type=\"Adult\" />"
      << "<applyTo species=\"Paper_Birch\" type=\"Snag\" />"
      << "<applyTo species=\"Western_Hemlock\" type=\"Adult\" />"
      << "<applyTo species=\"Western_Hemlock\" type=\"Snag\" />"
      << "<listPosition>3</listPosition>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>SnagDecayClassDynamics</behaviorName>"
      << "<version>2.0</version>"
      << "<listPosition>4</listPosition>"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Adult\" />"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Snag\" />"
      << "<applyTo species=\"Paper_Birch\" type=\"Adult\" />"
      << "<applyTo species=\"Paper_Birch\" type=\"Snag\" />"
      << "<applyTo species=\"Western_Hemlock\" type=\"Adult\" />"
      << "<applyTo species=\"Western_Hemlock\" type=\"Snag\" />"
      << "</behavior>"
      << "</behaviorList>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Paper_Birch\" />"
      << "<ha_applyToSpecies species=\"Western_Hemlock\" />"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_applyToSpecies species=\"Subalpine_Fir\" />"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_applyToSpecies species=\"Trembling_Aspen\" />"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>clear</ha_cutType>"
      << "<ha_cutAmountType>percent of density</ha_cutAmountType>"
      << "<ha_maxSnagDecayClass>1</ha_maxSnagDecayClass>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>100.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_percentSeedlingsDie>"
      << "<ha_psdVal species=\"Western_Hemlock\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Western_Redcedar\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Amabilis_Fir\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Subalpine_Fir\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Hybrid_Spruce\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Lodgepole_Pine\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Trembling_Aspen\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Black_Cottonwood\">100</ha_psdVal>"
      << "<ha_psdVal species=\"Paper_Birch\">100</ha_psdVal>"
      << "</ha_percentSeedlingsDie>";
  for (int i = 0; i < 22; i++) {
    for (int j = 0; j < 37; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "</Harvest1>"
      << "<ConstantGLI2>"
      << "<li_constGLI>100</li_constGLI>"
      << "</ConstantGLI2>"
      << "<StochasticMortality3>"
      << "<mo_stochasticMortRate>"
      << "<mo_smrVal species=\"Amabilis_Fir\">0.0</mo_smrVal>"
      << "<mo_smrVal species=\"Paper_Birch\">0.0</mo_smrVal>"
      << "<mo_smrVal species=\"Western_Hemlock\">0.0</mo_smrVal>"
      << "</mo_stochasticMortRate>"
      << "</StochasticMortality3>"
      << "<SnagDecayClassDynamics4>"
      << "<sd_snagDecompTreefallAlpha>-0.805</sd_snagDecompTreefallAlpha>"
      << "<sd_snagDecompTreefallBeta>"
      << "<sd_sdtbVal species=\"Amabilis_Fir\">0.000</sd_sdtbVal>"
      << "<sd_sdtbVal species=\"Paper_Birch\">0.000</sd_sdtbVal>"
      << "<sd_sdtbVal species=\"Western_Hemlock\">0.000</sd_sdtbVal>"
      << "</sd_snagDecompTreefallBeta>"
      << "<sd_snagDecompTreefallDelta>-0.016</sd_snagDecompTreefallDelta>"
      << "<sd_snagDecompTreefallTheta>-0.026</sd_snagDecompTreefallTheta>"
      << "<sd_snagDecompTreefallIota>3.389</sd_snagDecompTreefallIota>"
      << "<sd_snagDecompTreefallLambda>-0.084</sd_snagDecompTreefallLambda>"
      << "<sd_snagDecompSnagfallAlpha>5.691</sd_snagDecompSnagfallAlpha>"
      << "<sd_snagDecompSnagfallBeta>"
      << "<sd_sdsbVal species=\"Amabilis_Fir\">0.000</sd_sdsbVal>"
      << "<sd_sdsbVal species=\"Paper_Birch\">0.000</sd_sdsbVal>"
      << "<sd_sdsbVal species=\"Western_Hemlock\">0.000</sd_sdsbVal>"
      << "</sd_snagDecompSnagfallBeta>"
      << "<sd_snagDecompSnagfallGamma2>0.177</sd_snagDecompSnagfallGamma2>"
      << "<sd_snagDecompSnagfallGamma3>0.542</sd_snagDecompSnagfallGamma3>"
      << "<sd_snagDecompSnagfallGamma4>0.702</sd_snagDecompSnagfallGamma4>"
      << "<sd_snagDecompSnagfallGamma5>0.528</sd_snagDecompSnagfallGamma5>"
      << "<sd_snagDecompSnagfallZeta>-3.777</sd_snagDecompSnagfallZeta>"
      << "<sd_snagDecompSnagfallEta>0.531</sd_snagDecompSnagfallEta>"
      << "<sd_snagDecompSnagfallKappa>0.157</sd_snagDecompSnagfallKappa>"
      << "<sd_snagDecompLiveTo1Prob>0.290</sd_snagDecompLiveTo1Prob>"
      << "<sd_snagDecompLiveTo2Prob>0.229</sd_snagDecompLiveTo2Prob>"
      << "<sd_snagDecompLiveTo3Prob>0.196</sd_snagDecompLiveTo3Prob>"
      << "<sd_snagDecompLiveTo4Prob>0.124</sd_snagDecompLiveTo4Prob>"
      << "<sd_snagDecompLiveTo5Prob>0.161</sd_snagDecompLiveTo5Prob>"
      << "<sd_snagDecomp1To1Prob>0.045</sd_snagDecomp1To1Prob>"
      << "<sd_snagDecomp1To2Prob>0.186</sd_snagDecomp1To2Prob>"
      << "<sd_snagDecomp1To3Prob>0.329</sd_snagDecomp1To3Prob>"
      << "<sd_snagDecomp1To4Prob>0.166</sd_snagDecomp1To4Prob>"
      << "<sd_snagDecomp1To5Prob>0.274</sd_snagDecomp1To5Prob>"
      << "<sd_snagDecomp2To2Prob>0.165</sd_snagDecomp2To2Prob>"
      << "<sd_snagDecomp2To3Prob>0.379</sd_snagDecomp2To3Prob>"
      << "<sd_snagDecomp2To4Prob>0.204</sd_snagDecomp2To4Prob>"
      << "<sd_snagDecomp2To5Prob>0.252</sd_snagDecomp2To5Prob>"
      << "<sd_snagDecomp3To3Prob>0.351</sd_snagDecomp3To3Prob>"
      << "<sd_snagDecomp3To4Prob>0.346</sd_snagDecomp3To4Prob>"
      << "<sd_snagDecomp3To5Prob>0.303</sd_snagDecomp3To5Prob>"
      << "<sd_snagDecomp4To4Prob>0.527</sd_snagDecomp4To4Prob>"
      << "<sd_snagDecomp4To5Prob>0.473</sd_snagDecomp4To5Prob>"
      << "<sd_snagDecomp5To5Prob>1.000</sd_snagDecomp5To5Prob>"
      << "<sd_minSnagBreakHeight>6</sd_minSnagBreakHeight>"
      << "<sd_maxSnagBreakHeight>6</sd_maxSnagBreakHeight>"
      << "</SnagDecayClassDynamics4>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestXMLFile9()
/////////////////////////////////////////////////////////////////////////////
const char* WriteHarvestXMLFile9(bool bTallestFirst)
{
  using namespace std;
  const char *cFileString = "TestFile1.xml";

  //Open file to write to
  std::fstream oOut;
  oOut.open(cFileString, ios::out | ios::trunc);

  oOut << "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>"
      << "<paramFile fileCode=\"06010101\">"
      << "<plot>"
      << "<timesteps>3</timesteps>"
      << "<yearsPerTimestep>1</yearsPerTimestep>"
      << "<randomSeed>1</randomSeed>"
      << "<plot_lenX>200.0</plot_lenX>"
      << "<plot_lenY>200.0</plot_lenY>"
      << "<plot_precip_mm_yr>1150.645781</plot_precip_mm_yr>"
      << "<plot_temp_C>12.88171785</plot_temp_C>"
      << "<plot_latitude>55.37</plot_latitude>"
      << "</plot>"
      << "<trees>"
      << "<tr_speciesList>"
      << "<tr_species speciesName=\"Western_Hemlock\"/>"
      << "<tr_species speciesName=\"Western_Redcedar\"/>"
      << "<tr_species speciesName=\"Amabilis_Fir\"/>"
      << "<tr_species speciesName=\"Subalpine_Fir\"/>"
      << "<tr_species speciesName=\"Hybrid_Spruce\"/>"
      << "<tr_species speciesName=\"Lodgepole_Pine\"/>"
      << "<tr_species speciesName=\"Trembling_Aspen\"/>"
      << "<tr_species speciesName=\"Black_Cottonwood\"/>"
      << "<tr_species speciesName=\"Paper_Birch\"/>"
      << "</tr_speciesList>"
      << "<tr_seedDiam10Cm>0.1</tr_seedDiam10Cm>"
      << "<tr_minAdultDBH>"
      << "<tr_madVal species=\"Western_Hemlock\">10</tr_madVal>"
      << "<tr_madVal species=\"Western_Redcedar\">10</tr_madVal>"
      << "<tr_madVal species=\"Amabilis_Fir\">10</tr_madVal>"
      << "<tr_madVal species=\"Subalpine_Fir\">10</tr_madVal>"
      << "<tr_madVal species=\"Hybrid_Spruce\">10</tr_madVal>"
      << "<tr_madVal species=\"Lodgepole_Pine\">10</tr_madVal>"
      << "<tr_madVal species=\"Trembling_Aspen\">10</tr_madVal>"
      << "<tr_madVal species=\"Black_Cottonwood\">10</tr_madVal>"
      << "<tr_madVal species=\"Paper_Birch\">10</tr_madVal>"
      << "</tr_minAdultDBH>"
      << "<tr_maxSeedlingHeight>"
      << "<tr_mshVal species=\"Western_Hemlock\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Western_Redcedar\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Amabilis_Fir\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Subalpine_Fir\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Hybrid_Spruce\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Lodgepole_Pine\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Trembling_Aspen\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Black_Cottonwood\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Paper_Birch\">1.35</tr_mshVal>"
      << "</tr_maxSeedlingHeight>";

  oOut << "<tr_treemapFile>" << WriteHarvestRun9TreeMap() << "</tr_treemapFile>";

  oOut << "</trees>"
      << "<allometry>"
      << "<tr_canopyHeight>"
      << "<tr_chVal species=\"Western_Hemlock\">39.48</tr_chVal>"
      << "<tr_chVal species=\"Western_Redcedar\">39.54</tr_chVal>"
      << "<tr_chVal species=\"Amabilis_Fir\">40</tr_chVal>"
      << "<tr_chVal species=\"Subalpine_Fir\">40</tr_chVal>"
      << "<tr_chVal species=\"Hybrid_Spruce\">45</tr_chVal>"
      << "<tr_chVal species=\"Lodgepole_Pine\">40</tr_chVal>"
      << "<tr_chVal species=\"Trembling_Aspen\">39.14</tr_chVal>"
      << "<tr_chVal species=\"Black_Cottonwood\">39.47</tr_chVal>"
      << "<tr_chVal species=\"Paper_Birch\">33.18</tr_chVal>"
      << "</tr_canopyHeight>"
      << "<tr_stdAsympCrownRad>"
      << "<tr_sacrVal species=\"Western_Hemlock\">0.0549</tr_sacrVal>"
      << "<tr_sacrVal species=\"Western_Redcedar\">0.0614</tr_sacrVal>"
      << "<tr_sacrVal species=\"Amabilis_Fir\">0.0242</tr_sacrVal>"
      << "<tr_sacrVal species=\"Subalpine_Fir\">0.0251</tr_sacrVal>"
      << "<tr_sacrVal species=\"Hybrid_Spruce\">0.0239</tr_sacrVal>"
      << "<tr_sacrVal species=\"Lodgepole_Pine\">0.0303</tr_sacrVal>"
      << "<tr_sacrVal species=\"Trembling_Aspen\">0.0328</tr_sacrVal>"
      << "<tr_sacrVal species=\"Black_Cottonwood\">0.0247</tr_sacrVal>"
      << "<tr_sacrVal species=\"Paper_Birch\">0.0484</tr_sacrVal>"
      << "</tr_stdAsympCrownRad>"
      << "<tr_stdCrownRadExp>"
      << "<tr_screVal species=\"Western_Hemlock\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Western_Redcedar\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Amabilis_Fir\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Subalpine_Fir\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Hybrid_Spruce\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Lodgepole_Pine\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Trembling_Aspen\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Black_Cottonwood\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Paper_Birch\">1.0</tr_screVal>"
      << "</tr_stdCrownRadExp>"
      << "<tr_stdMaxCrownRad>"
      << "<tr_smcrVal species=\"Western_Hemlock\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Western_Redcedar\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Amabilis_Fir\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Subalpine_Fir\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Hybrid_Spruce\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Lodgepole_Pine\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Trembling_Aspen\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Black_Cottonwood\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Paper_Birch\">10</tr_smcrVal>"
      << "</tr_stdMaxCrownRad>"
      << "<tr_conversionDiam10ToDBH>"
      << "<tr_cdtdVal species=\"Western_Hemlock\">0.8008</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Western_Redcedar\">0.5944</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Amabilis_Fir\">0.7059</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Subalpine_Fir\">0.7776</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Hybrid_Spruce\">0.6933</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Lodgepole_Pine\">0.8014</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Trembling_Aspen\">0.7992</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Black_Cottonwood\">0.7926</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Paper_Birch\">0.7803</tr_cdtdVal>"
      << "</tr_conversionDiam10ToDBH>"
      << "<tr_interceptDiam10ToDBH>"
      << "<tr_idtdVal species=\"Western_Hemlock\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Western_Redcedar\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Amabilis_Fir\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Subalpine_Fir\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Hybrid_Spruce\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Lodgepole_Pine\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Trembling_Aspen\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Black_Cottonwood\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Paper_Birch\">0</tr_idtdVal>"
      << "</tr_interceptDiam10ToDBH>"
      << "<tr_stdAsympCrownHt>"
      << "<tr_sachVal species=\"Western_Hemlock\">0.389</tr_sachVal>"
      << "<tr_sachVal species=\"Western_Redcedar\">0.368</tr_sachVal>"
      << "<tr_sachVal species=\"Amabilis_Fir\">0.464</tr_sachVal>"
      << "<tr_sachVal species=\"Subalpine_Fir\">0.454</tr_sachVal>"
      << "<tr_sachVal species=\"Hybrid_Spruce\">0.405</tr_sachVal>"
      << "<tr_sachVal species=\"Lodgepole_Pine\">0.201</tr_sachVal>"
      << "<tr_sachVal species=\"Trembling_Aspen\">0.301</tr_sachVal>"
      << "<tr_sachVal species=\"Black_Cottonwood\">0.42</tr_sachVal>"
      << "<tr_sachVal species=\"Paper_Birch\">0.315</tr_sachVal>"
      << "</tr_stdAsympCrownHt>"
      << "<tr_stdCrownHtExp>"
      << "<tr_scheVal species=\"Western_Hemlock\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Western_Redcedar\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Amabilis_Fir\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Subalpine_Fir\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Hybrid_Spruce\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Lodgepole_Pine\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Trembling_Aspen\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Black_Cottonwood\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Paper_Birch\">1.0</tr_scheVal>"
      << "</tr_stdCrownHtExp>"
      << "<tr_slopeOfHeight-Diam10>"
      << "<tr_sohdVal species=\"Western_Hemlock\">0.03418</tr_sohdVal>"
      << "<tr_sohdVal species=\"Western_Redcedar\">0.0269</tr_sohdVal>"
      << "<tr_sohdVal species=\"Amabilis_Fir\">0.02871</tr_sohdVal>"
      << "<tr_sohdVal species=\"Subalpine_Fir\">0.02815</tr_sohdVal>"
      << "<tr_sohdVal species=\"Hybrid_Spruce\">0.02871</tr_sohdVal>"
      << "<tr_sohdVal species=\"Lodgepole_Pine\">0.03224</tr_sohdVal>"
      << "<tr_sohdVal species=\"Trembling_Aspen\">0.04796</tr_sohdVal>"
      << "<tr_sohdVal species=\"Black_Cottonwood\">0.04681</tr_sohdVal>"
      << "<tr_sohdVal species=\"Paper_Birch\">0.04101</tr_sohdVal>"
      << "</tr_slopeOfHeight-Diam10>"
      << "<tr_slopeOfAsymHeight>"
      << "<tr_soahVal species=\"Western_Hemlock\">0.0299</tr_soahVal>"
      << "<tr_soahVal species=\"Western_Redcedar\">0.0241</tr_soahVal>"
      << "<tr_soahVal species=\"Amabilis_Fir\">0.0263</tr_soahVal>"
      << "<tr_soahVal species=\"Subalpine_Fir\">0.0264</tr_soahVal>"
      << "<tr_soahVal species=\"Hybrid_Spruce\">0.0264</tr_soahVal>"
      << "<tr_soahVal species=\"Lodgepole_Pine\">0.0333</tr_soahVal>"
      << "<tr_soahVal species=\"Trembling_Aspen\">0.0352</tr_soahVal>"
      << "<tr_soahVal species=\"Black_Cottonwood\">0.0347</tr_soahVal>"
      << "<tr_soahVal species=\"Paper_Birch\">0.0454</tr_soahVal>"
      << "</tr_slopeOfAsymHeight>"
      << "<tr_whatSeedlingHeightDiam>"
      << "<tr_wsehdVal species=\"Western_Hemlock\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Western_Redcedar\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Amabilis_Fir\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Subalpine_Fir\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Hybrid_Spruce\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Lodgepole_Pine\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Trembling_Aspen\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Black_Cottonwood\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Paper_Birch\">0</tr_wsehdVal>"
      << "</tr_whatSeedlingHeightDiam>"
      << "<tr_whatSaplingHeightDiam>"
      << "<tr_wsahdVal species=\"Western_Hemlock\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Western_Redcedar\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Amabilis_Fir\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Subalpine_Fir\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Hybrid_Spruce\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Lodgepole_Pine\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Trembling_Aspen\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Black_Cottonwood\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Paper_Birch\">0</tr_wsahdVal>"
      << "</tr_whatSaplingHeightDiam>"
      << "<tr_whatAdultHeightDiam>"
      << "<tr_wahdVal species=\"Western_Hemlock\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Western_Redcedar\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Amabilis_Fir\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Subalpine_Fir\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Hybrid_Spruce\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Lodgepole_Pine\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Trembling_Aspen\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Black_Cottonwood\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Paper_Birch\">0</tr_wahdVal>"
      << "</tr_whatAdultHeightDiam>"
      << "<tr_whatAdultCrownRadDiam>"
      << "<tr_wacrdVal species=\"Western_Hemlock\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Western_Redcedar\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Amabilis_Fir\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Subalpine_Fir\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Hybrid_Spruce\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Lodgepole_Pine\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Trembling_Aspen\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Black_Cottonwood\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Paper_Birch\">0</tr_wacrdVal>"
      << "</tr_whatAdultCrownRadDiam>"
      << "<tr_whatAdultCrownHeightHeight>"
      << "<tr_wachhVal species=\"Western_Hemlock\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Western_Redcedar\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Amabilis_Fir\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Subalpine_Fir\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Hybrid_Spruce\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Lodgepole_Pine\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Trembling_Aspen\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Black_Cottonwood\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Paper_Birch\">0</tr_wachhVal>"
      << "</tr_whatAdultCrownHeightHeight>"
      << "<tr_whatSaplingCrownRadDiam>"
      << "<tr_wscrdVal species=\"Western_Hemlock\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Western_Redcedar\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Amabilis_Fir\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Subalpine_Fir\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Hybrid_Spruce\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Lodgepole_Pine\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Trembling_Aspen\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Black_Cottonwood\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Paper_Birch\">0</tr_wscrdVal>"
      << "</tr_whatSaplingCrownRadDiam>"
      << "<tr_whatSaplingCrownHeightHeight>"
      << "<tr_wschhVal species=\"Western_Hemlock\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Western_Redcedar\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Amabilis_Fir\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Subalpine_Fir\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Hybrid_Spruce\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Lodgepole_Pine\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Trembling_Aspen\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Black_Cottonwood\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Paper_Birch\">0</tr_wschhVal>"
      << "</tr_whatSaplingCrownHeightHeight>"
      << "</allometry>";

  oOut << "<behaviorList>"
      << "<behavior>"
      << "<behaviorName>Harvest</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>1</listPosition>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>QualityVigorClassifier</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>2</listPosition>"
      << "<applyTo species=\"Western_Hemlock\" type=\"Adult\"/>"
      << "<applyTo species=\"Western_Redcedar\" type=\"Adult\"/>"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Adult\"/>"
      << "<applyTo species=\"Subalpine_Fir\" type=\"Adult\"/>"
      << "<applyTo species=\"Hybrid_Spruce\" type=\"Adult\"/>"
      << "<applyTo species=\"Lodgepole_Pine\" type=\"Adult\"/>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Adult\"/>"
      << "<applyTo species=\"Black_Cottonwood\" type=\"Adult\"/>"
      << "<applyTo species=\"Paper_Birch\" type=\"Adult\"/>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>ConstRadialGrowth</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>3</listPosition>"
      << "<applyTo species=\"Western_Hemlock\" type=\"Adult\"/>"
      << "<applyTo species=\"Western_Redcedar\" type=\"Adult\"/>"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Adult\"/>"
      << "<applyTo species=\"Subalpine_Fir\" type=\"Adult\"/>"
      << "<applyTo species=\"Hybrid_Spruce\" type=\"Adult\"/>"
      << "<applyTo species=\"Lodgepole_Pine\" type=\"Adult\"/>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Adult\"/>"
      << "<applyTo species=\"Black_Cottonwood\" type=\"Adult\"/>"
      << "<applyTo species=\"Paper_Birch\" type=\"Adult\"/>"
      << "<applyTo species=\"Western_Hemlock\" type=\"Sapling\"/>"
      << "<applyTo species=\"Western_Redcedar\" type=\"Sapling\"/>"
      << "<applyTo species=\"Amabilis_Fir\" type=\"Sapling\"/>"
      << "<applyTo species=\"Subalpine_Fir\" type=\"Sapling\"/>"
      << "<applyTo species=\"Hybrid_Spruce\" type=\"Sapling\"/>"
      << "<applyTo species=\"Lodgepole_Pine\" type=\"Sapling\"/>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Sapling\"/>"
      << "<applyTo species=\"Black_Cottonwood\" type=\"Sapling\"/>"
      << "<applyTo species=\"Paper_Birch\" type=\"Sapling\"/>"
      << "</behavior>"
      << "<behavior>"
      << "<behaviorName>InsectInfestation</behaviorName>"
      << "<version>1</version>"
      << "<listPosition>4</listPosition>"
      << "<applyTo species=\"Subalpine_Fir\" type=\"Adult\"/>"
      << "<applyTo species=\"Hybrid_Spruce\" type=\"Adult\"/>"
      << "<applyTo species=\"Lodgepole_Pine\" type=\"Adult\"/>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Adult\"/>"
      << "<applyTo species=\"Black_Cottonwood\" type=\"Adult\"/>"
      << "<applyTo species=\"Paper_Birch\" type=\"Adult\"/>"
      << "<applyTo species=\"Subalpine_Fir\" type=\"Sapling\"/>"
      << "<applyTo species=\"Hybrid_Spruce\" type=\"Sapling\"/>"
      << "<applyTo species=\"Lodgepole_Pine\" type=\"Sapling\"/>"
      << "<applyTo species=\"Trembling_Aspen\" type=\"Sapling\"/>"
      << "<applyTo species=\"Black_Cottonwood\" type=\"Sapling\"/>"
      << "<applyTo species=\"Paper_Birch\" type=\"Sapling\"/>"
      << "</behavior>"
      << "</behaviorList>";
  oOut << "<QualityVigorClassifier2>"
      << "<ma_classifierVigBeta0>"
      << "<ma_cvb0Val species=\"Western_Hemlock\">0.1</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Western_Redcedar\">0.1</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Amabilis_Fir\">0.1</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Subalpine_Fir\">0</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Hybrid_Spruce\">0.3</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Lodgepole_Pine\">0.4</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Black_Cottonwood\">0.1</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Paper_Birch\">0.1</ma_cvb0Val>"
      << "<ma_cvb0Val species=\"Trembling_Aspen\">0.1</ma_cvb0Val>"
      << "</ma_classifierVigBeta0>"
      << "<ma_classifierVigBeta11>"
      << "<ma_cvb11Val species=\"Western_Hemlock\">0.2</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Western_Redcedar\">0.2</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Amabilis_Fir\">0.2</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Subalpine_Fir\">2.35</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Hybrid_Spruce\">0.1</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Lodgepole_Pine\">2.43</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Black_Cottonwood\">0.2</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Paper_Birch\">0.2</ma_cvb11Val>"
      << "<ma_cvb11Val species=\"Trembling_Aspen\">0.2</ma_cvb11Val>"
      << "</ma_classifierVigBeta11>"
      << "<ma_classifierVigBeta12>"
      << "<ma_cvb12Val species=\"Western_Hemlock\">-2.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Western_Redcedar\">-2.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Amabilis_Fir\">-2.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Subalpine_Fir\">1.12</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Hybrid_Spruce\">0.32</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Lodgepole_Pine\">1.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Black_Cottonwood\">-2.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Paper_Birch\">-2.3</ma_cvb12Val>"
      << "<ma_cvb12Val species=\"Trembling_Aspen\">-2.3</ma_cvb12Val>"
      << "</ma_classifierVigBeta12>"
      << "<ma_classifierVigBeta13>"
      << "<ma_cvb13Val species=\"Western_Hemlock\">0.13</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Western_Redcedar\">0.13</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Amabilis_Fir\">0.13</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Subalpine_Fir\">1</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Hybrid_Spruce\">-0.2</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Lodgepole_Pine\">1</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Black_Cottonwood\">0.13</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Paper_Birch\">0.13</ma_cvb13Val>"
      << "<ma_cvb13Val species=\"Trembling_Aspen\">0.13</ma_cvb13Val>"
      << "</ma_classifierVigBeta13>"
      << "<ma_classifierVigBeta14>"
      << "<ma_cvb14Val species=\"Western_Hemlock\">0.9</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Western_Redcedar\">0.9</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Amabilis_Fir\">0.9</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Subalpine_Fir\">0</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Hybrid_Spruce\">-1</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Lodgepole_Pine\">0</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Black_Cottonwood\">0.9</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Paper_Birch\">0.9</ma_cvb14Val>"
      << "<ma_cvb14Val species=\"Trembling_Aspen\">0.9</ma_cvb14Val>"
      << "</ma_classifierVigBeta14>"
      << "<ma_classifierVigBeta15>"
      << "<ma_cvb15Val species=\"Western_Hemlock\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Western_Redcedar\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Amabilis_Fir\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Subalpine_Fir\">0.25</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Hybrid_Spruce\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Lodgepole_Pine\">-0.45</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Black_Cottonwood\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Paper_Birch\">1</ma_cvb15Val>"
      << "<ma_cvb15Val species=\"Trembling_Aspen\">1</ma_cvb15Val>"
      << "</ma_classifierVigBeta15>"
      << "<ma_classifierVigBeta16>"
      << "<ma_cvb16Val species=\"Western_Hemlock\">1</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Western_Redcedar\">1</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Amabilis_Fir\">1</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Subalpine_Fir\">0.36</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Hybrid_Spruce\">0</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Lodgepole_Pine\">0.46</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Black_Cottonwood\">1</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Paper_Birch\">1</ma_cvb16Val>"
      << "<ma_cvb16Val species=\"Trembling_Aspen\">1</ma_cvb16Val>"
      << "</ma_classifierVigBeta16>"
      << "<ma_classifierVigBeta2>"
      << "<ma_cvb2Val species=\"Western_Hemlock\">0.01</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Western_Redcedar\">0.01</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Amabilis_Fir\">0.01</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Subalpine_Fir\">0.02</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Hybrid_Spruce\">0.04</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Lodgepole_Pine\">0.1</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Black_Cottonwood\">0.01</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Paper_Birch\">0.01</ma_cvb2Val>"
      << "<ma_cvb2Val species=\"Trembling_Aspen\">0.01</ma_cvb2Val>"
      << "</ma_classifierVigBeta2>"
      << "<ma_classifierVigBeta3>"
      << "<ma_cvb3Val species=\"Western_Hemlock\">0.001</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Western_Redcedar\">0.001</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Amabilis_Fir\">0.001</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Subalpine_Fir\">0.2</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Hybrid_Spruce\">0.3</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Lodgepole_Pine\">0.4</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Black_Cottonwood\">0.001</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Paper_Birch\">0.001</ma_cvb3Val>"
      << "<ma_cvb3Val species=\"Trembling_Aspen\">0.001</ma_cvb3Val>"
      << "</ma_classifierVigBeta3>"
      << "<ma_classifierQualBeta0>"
      << "<ma_cqb0Val species=\"Western_Hemlock\">0.25</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Western_Redcedar\">0.25</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Amabilis_Fir\">0.25</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Subalpine_Fir\">1.13</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Hybrid_Spruce\">0</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Lodgepole_Pine\">1.15</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Black_Cottonwood\">0.25</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Paper_Birch\">0.25</ma_cqb0Val>"
      << "<ma_cqb0Val species=\"Trembling_Aspen\">0.25</ma_cqb0Val>"
      << "</ma_classifierQualBeta0>"
      << "<ma_classifierQualBeta11>"
      << "<ma_cqb11Val species=\"Western_Hemlock\">0.36</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Western_Redcedar\">0.36</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Amabilis_Fir\">0.36</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Subalpine_Fir\">0</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Hybrid_Spruce\">0.4</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Lodgepole_Pine\">0</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Black_Cottonwood\">0.36</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Paper_Birch\">0.36</ma_cqb11Val>"
      << "<ma_cqb11Val species=\"Trembling_Aspen\">0.36</ma_cqb11Val>"
      << "</ma_classifierQualBeta11>"
      << "<ma_classifierQualBeta12>"
      << "<ma_cqb12Val species=\"Western_Hemlock\">0.02</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Western_Redcedar\">0.02</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Amabilis_Fir\">0.02</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Subalpine_Fir\">10</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Hybrid_Spruce\">0.3</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Lodgepole_Pine\">30</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Black_Cottonwood\">30</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Paper_Birch\">30</ma_cqb12Val>"
      << "<ma_cqb12Val species=\"Trembling_Aspen\">30</ma_cqb12Val>"
      << "</ma_classifierQualBeta12>"
      << "<ma_classifierQualBeta13>"
      << "<ma_cqb13Val species=\"Western_Hemlock\">0.2</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Western_Redcedar\">0.2</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Amabilis_Fir\">0.2</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Subalpine_Fir\">10</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Hybrid_Spruce\">-0.3</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Lodgepole_Pine\">30</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Black_Cottonwood\">0.2</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Paper_Birch\">0.2</ma_cqb13Val>"
      << "<ma_cqb13Val species=\"Trembling_Aspen\">0.2</ma_cqb13Val>"
      << "</ma_classifierQualBeta13>"
      << "<ma_classifierQualBeta14>"
      << "<ma_cqb14Val species=\"Western_Hemlock\">-0.2</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Western_Redcedar\">-0.2</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Amabilis_Fir\">-0.2</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Subalpine_Fir\">10</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Hybrid_Spruce\">-0.4</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Lodgepole_Pine\">30</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Black_Cottonwood\">-0.2</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Paper_Birch\">-0.2</ma_cqb14Val>"
      << "<ma_cqb14Val species=\"Trembling_Aspen\">-0.2</ma_cqb14Val>"
      << "</ma_classifierQualBeta14>"
      << "<ma_classifierQualBeta2>"
      << "<ma_cqb2Val species=\"Western_Hemlock\">-0.2</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Western_Redcedar\">-0.2</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Amabilis_Fir\">-0.2</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Subalpine_Fir\">10</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Hybrid_Spruce\">0</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Lodgepole_Pine\">30</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Black_Cottonwood\">30</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Paper_Birch\">30</ma_cqb2Val>"
      << "<ma_cqb2Val species=\"Trembling_Aspen\">30</ma_cqb2Val>"
      << "</ma_classifierQualBeta2>"
      << "<ma_classifierQualBeta3>"
      << "<ma_cqb3Val species=\"Western_Hemlock\">1</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Western_Redcedar\">1</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Amabilis_Fir\">1</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Subalpine_Fir\">10</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Hybrid_Spruce\">0.1</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Lodgepole_Pine\">30</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Black_Cottonwood\">30</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Paper_Birch\">30</ma_cqb3Val>"
      << "<ma_cqb3Val species=\"Trembling_Aspen\">30</ma_cqb3Val>"
      << "</ma_classifierQualBeta3>"
      << "<ma_classifierNewAdultProbVigorous>"
      << "<ma_cnapvVal species=\"Western_Hemlock\">0.1</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Western_Redcedar\">0.1</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Amabilis_Fir\">0.1</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Subalpine_Fir\">0.25</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Hybrid_Spruce\">0.5</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Lodgepole_Pine\">0.74</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Black_Cottonwood\">0.1</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Paper_Birch\">0.1</ma_cnapvVal>"
      << "<ma_cnapvVal species=\"Trembling_Aspen\">0.1</ma_cnapvVal>"
      << "</ma_classifierNewAdultProbVigorous>"
      << "<ma_classifierNewAdultProbSawlog>"
      << "<ma_cnapsVal species=\"Western_Hemlock\">0.9</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Western_Redcedar\">0.9</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Amabilis_Fir\">0.9</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Subalpine_Fir\">0.25</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Hybrid_Spruce\">0.3</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Lodgepole_Pine\">0.74</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Black_Cottonwood\">0.9</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Paper_Birch\">0.9</ma_cnapsVal>"
      << "<ma_cnapsVal species=\"Trembling_Aspen\">0.9</ma_cnapsVal>"
      << "</ma_classifierNewAdultProbSawlog>"
      << "<ma_classifierDeciduous>"
      << "<ma_cdVal species=\"Western_Hemlock\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Western_Redcedar\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Amabilis_Fir\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Subalpine_Fir\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Hybrid_Spruce\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Lodgepole_Pine\">0</ma_cdVal>"
      << "<ma_cdVal species=\"Black_Cottonwood\">1</ma_cdVal>"
      << "<ma_cdVal species=\"Paper_Birch\">1</ma_cdVal>"
      << "<ma_cdVal species=\"Trembling_Aspen\">1</ma_cdVal>"
      << "</ma_classifierDeciduous>"
      << "</QualityVigorClassifier2>"
      << "<Harvest1>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Western_Redcedar\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>87.0</ha_high>"
      << "<ha_amountToCut>10.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>Growth</ha_name>"
      << "<ha_type>float</ha_type>"
      << "<ha_min>5</ha_min>"
      << "<ha_max>10</ha_max>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Amabilis_Fir\" />"
      << "<ha_applyToSpecies species=\"Subalpine_Fir\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>10.0</ha_low>"
      << "<ha_high>50.0</ha_high>"
      << "<ha_amountToCut>5.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>YearsInfested</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>1</ha_min>"
      << "<ha_max>100</ha_max>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>vigorous</ha_name>"
      << "<ha_type>bool</ha_type>"
      << "<ha_min>1</ha_min>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Hybrid_Spruce\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>percent of basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>85.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>YearsInfested</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>3</ha_min>"
      << "<ha_max>100</ha_max>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>vigorous</ha_name>"
      << "<ha_type>bool</ha_type>"
      << "<ha_min>1</ha_min>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>Growth</ha_name>"
      << "<ha_type>float</ha_type>"
      << "<ha_min>5</ha_min>"
      << "<ha_max>10</ha_max>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Trembling_Aspen\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_dbhRange>"
      << "<ha_low>10.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>2.0</ha_amountToCut>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>3</ha_min>"
      << "<ha_max>3</ha_max>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>4</ha_min>"
      << "<ha_max>4</ha_max>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Black_Cottonwood\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>4.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>3</ha_min>"
      << "<ha_max>3</ha_max>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>4</ha_min>"
      << "<ha_max>4</ha_max>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Paper_Birch\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute basal area</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>10.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>7.0</ha_amountToCut>"
      << "</ha_dbhRange>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>3</ha_min>"
      << "<ha_max>3</ha_max>"
      << "</ha_priority>"
      << "<ha_priority>"
      << "<ha_name>treeclass</ha_name>"
      << "<ha_type>int</ha_type>"
      << "<ha_min>4</ha_min>"
      << "<ha_max>4</ha_max>"
      << "</ha_priority>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
      << "<ha_cutEvent>"
      << "<ha_applyToSpecies species=\"Lodgepole_Pine\" />"
      << "<ha_timestep>1</ha_timestep>"
      << "<ha_cutType>partial</ha_cutType>"
      << "<ha_cutAmountType>absolute density</ha_cutAmountType>"
      << "<ha_tallestFirst>" << bTallestFirst << "</ha_tallestFirst>"
      << "<ha_dbhRange>"
      << "<ha_low>0.0</ha_low>"
      << "<ha_high>3000.0</ha_high>"
      << "<ha_amountToCut>10.0</ha_amountToCut>"
      << "</ha_dbhRange>";
  for (int i = 0; i < 25; i++) {
    for (int j = 0; j < 25; j++) {
      oOut << "<ha_applyToCell x=\"" << i << "\" y=\"" << j << "\" /> ";
    }
  }
  oOut << "</ha_cutEvent>"
       << "</Harvest1>";
  oOut << "<InsectInfestation4>"
      << "<di_insectIntercept>"
      << "<di_iiVal species=\"Subalpine_Fir\">0</di_iiVal>"
      << "<di_iiVal species=\"Hybrid_Spruce\">0.01</di_iiVal>"
      << "<di_iiVal species=\"Lodgepole_Pine\">0.01</di_iiVal>"
      << "<di_iiVal species=\"Trembling_Aspen\">0.01</di_iiVal>"
      << "<di_iiVal species=\"Black_Cottonwood\">0.01</di_iiVal>"
      << "<di_iiVal species=\"Paper_Birch\">0.01</di_iiVal>"
      << "</di_insectIntercept>"
      << "<di_insectMaxInfestation>"
      << "<di_imiVal species=\"Subalpine_Fir\">1</di_imiVal>"
      << "<di_imiVal species=\"Hybrid_Spruce\">0.6</di_imiVal>"
      << "<di_imiVal species=\"Lodgepole_Pine\">1</di_imiVal>"
      << "<di_imiVal species=\"Trembling_Aspen\">1</di_imiVal>"
      << "<di_imiVal species=\"Black_Cottonwood\">1</di_imiVal>"
      << "<di_imiVal species=\"Paper_Birch\">1</di_imiVal>"
      << "</di_insectMaxInfestation>"
      << "<di_insectX0>"
      << "<di_ix0Val species=\"Subalpine_Fir\">11</di_ix0Val>"
      << "<di_ix0Val species=\"Hybrid_Spruce\">8</di_ix0Val>"
      << "<di_ix0Val species=\"Lodgepole_Pine\">5</di_ix0Val>"
      << "<di_ix0Val species=\"Trembling_Aspen\">9</di_ix0Val>"
      << "<di_ix0Val species=\"Black_Cottonwood\">5</di_ix0Val>"
      << "<di_ix0Val species=\"Paper_Birch\">9</di_ix0Val>"
      << "</di_insectX0>"
      << "<di_insectXb>"
      << "<di_ixbVal species=\"Subalpine_Fir\">-8</di_ixbVal>"
      << "<di_ixbVal species=\"Hybrid_Spruce\">-10</di_ixbVal>"
      << "<di_ixbVal species=\"Lodgepole_Pine\">-4</di_ixbVal>"
      << "<di_ixbVal species=\"Trembling_Aspen\">-6</di_ixbVal>"
      << "<di_ixbVal species=\"Black_Cottonwood\">-4</di_ixbVal>"
      << "<di_ixbVal species=\"Paper_Birch\">-6</di_ixbVal>"
      << "</di_insectXb>"
      << "<di_insectMinDBH>"
      << "<di_imdVal species=\"Subalpine_Fir\">2.2</di_imdVal>"
      << "<di_imdVal species=\"Hybrid_Spruce\">2.2</di_imdVal>"
      << "<di_imdVal species=\"Lodgepole_Pine\">2.2</di_imdVal>"
      << "<di_imdVal species=\"Trembling_Aspen\">2.2</di_imdVal>"
      << "<di_imdVal species=\"Black_Cottonwood\">2.2</di_imdVal>"
      << "<di_imdVal species=\"Paper_Birch\">2.2</di_imdVal>"
      << "</di_insectMinDBH>"
      << "<di_insectStartTimestep>10</di_insectStartTimestep>"
      << "</InsectInfestation4>"
      << "<ConstRadialGrowth3>"
      << "<gr_adultConstRadialInc>"
      << "<gr_acriVal species=\"Western_Hemlock\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Western_Redcedar\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Amabilis_Fir\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Subalpine_Fir\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Hybrid_Spruce\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Lodgepole_Pine\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Trembling_Aspen\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Black_Cottonwood\">0</gr_acriVal>"
      << "<gr_acriVal species=\"Paper_Birch\">0</gr_acriVal>"
      << "</gr_adultConstRadialInc>"
      << "</ConstRadialGrowth3>"
      << "</paramFile>";

  oOut.close();

  return cFileString;
}

/////////////////////////////////////////////////////////////////////////////
// WriteHarvestFileBeginning()
/////////////////////////////////////////////////////////////////////////////
void WriteHarvestFileBeginning(std::fstream &oOut, int iRandomSeed) {

  oOut << "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>"
      << "<paramFile fileCode=\"06010101\">"
      << "<plot>"
      << "<timesteps>3</timesteps>"
      << "<yearsPerTimestep>1</yearsPerTimestep>"
      << "<randomSeed>" << iRandomSeed << "</randomSeed>"
      << "<plot_lenX>200.0</plot_lenX>"
      << "<plot_lenY>200.0</plot_lenY>"
      << "<plot_precip_mm_yr>1150.645781</plot_precip_mm_yr>"
      << "<plot_temp_C>12.88171785</plot_temp_C>"
      << "<plot_latitude>55.37</plot_latitude>"
      << "</plot>"
      << "<trees>"
      << "<tr_speciesList>"
      << "<tr_species speciesName=\"Western_Hemlock\"/>"
      << "<tr_species speciesName=\"Western_Redcedar\"/>"
      << "<tr_species speciesName=\"Amabilis_Fir\"/>"
      << "<tr_species speciesName=\"Subalpine_Fir\"/>"
      << "<tr_species speciesName=\"Hybrid_Spruce\"/>"
      << "<tr_species speciesName=\"Lodgepole_Pine\"/>"
      << "<tr_species speciesName=\"Trembling_Aspen\"/>"
      << "<tr_species speciesName=\"Black_Cottonwood\"/>"
      << "<tr_species speciesName=\"Paper_Birch\"/>"
      << "</tr_speciesList>"
      << "<tr_seedDiam10Cm>0.1</tr_seedDiam10Cm>"
      << "<tr_minAdultDBH>"
      << "<tr_madVal species=\"Western_Hemlock\">10</tr_madVal>"
      << "<tr_madVal species=\"Western_Redcedar\">10</tr_madVal>"
      << "<tr_madVal species=\"Amabilis_Fir\">10</tr_madVal>"
      << "<tr_madVal species=\"Subalpine_Fir\">10</tr_madVal>"
      << "<tr_madVal species=\"Hybrid_Spruce\">10</tr_madVal>"
      << "<tr_madVal species=\"Lodgepole_Pine\">10</tr_madVal>"
      << "<tr_madVal species=\"Trembling_Aspen\">10</tr_madVal>"
      << "<tr_madVal species=\"Black_Cottonwood\">10</tr_madVal>"
      << "<tr_madVal species=\"Paper_Birch\">10</tr_madVal>"
      << "</tr_minAdultDBH>"
      << "<tr_maxSeedlingHeight>"
      << "<tr_mshVal species=\"Western_Hemlock\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Western_Redcedar\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Amabilis_Fir\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Subalpine_Fir\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Hybrid_Spruce\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Lodgepole_Pine\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Trembling_Aspen\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Black_Cottonwood\">1.35</tr_mshVal>"
      << "<tr_mshVal species=\"Paper_Birch\">1.35</tr_mshVal>"
      << "</tr_maxSeedlingHeight>";

  WriteHarvestTreeMap(oOut);

  oOut << "</trees>"
      << "<allometry>"
      << "<tr_canopyHeight>"
      << "<tr_chVal species=\"Western_Hemlock\">39.48</tr_chVal>"
      << "<tr_chVal species=\"Western_Redcedar\">39.54</tr_chVal>"
      << "<tr_chVal species=\"Amabilis_Fir\">40</tr_chVal>"
      << "<tr_chVal species=\"Subalpine_Fir\">40</tr_chVal>"
      << "<tr_chVal species=\"Hybrid_Spruce\">45</tr_chVal>"
      << "<tr_chVal species=\"Lodgepole_Pine\">40</tr_chVal>"
      << "<tr_chVal species=\"Trembling_Aspen\">39.14</tr_chVal>"
      << "<tr_chVal species=\"Black_Cottonwood\">39.47</tr_chVal>"
      << "<tr_chVal species=\"Paper_Birch\">33.18</tr_chVal>"
      << "</tr_canopyHeight>"
      << "<tr_stdAsympCrownRad>"
      << "<tr_sacrVal species=\"Western_Hemlock\">0.0549</tr_sacrVal>"
      << "<tr_sacrVal species=\"Western_Redcedar\">0.0614</tr_sacrVal>"
      << "<tr_sacrVal species=\"Amabilis_Fir\">0.0242</tr_sacrVal>"
      << "<tr_sacrVal species=\"Subalpine_Fir\">0.0251</tr_sacrVal>"
      << "<tr_sacrVal species=\"Hybrid_Spruce\">0.0239</tr_sacrVal>"
      << "<tr_sacrVal species=\"Lodgepole_Pine\">0.0303</tr_sacrVal>"
      << "<tr_sacrVal species=\"Trembling_Aspen\">0.0328</tr_sacrVal>"
      << "<tr_sacrVal species=\"Black_Cottonwood\">0.0247</tr_sacrVal>"
      << "<tr_sacrVal species=\"Paper_Birch\">0.0484</tr_sacrVal>"
      << "</tr_stdAsympCrownRad>"
      << "<tr_stdCrownRadExp>"
      << "<tr_screVal species=\"Western_Hemlock\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Western_Redcedar\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Amabilis_Fir\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Subalpine_Fir\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Hybrid_Spruce\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Lodgepole_Pine\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Trembling_Aspen\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Black_Cottonwood\">1.0</tr_screVal>"
      << "<tr_screVal species=\"Paper_Birch\">1.0</tr_screVal>"
      << "</tr_stdCrownRadExp>"
      << "<tr_stdMaxCrownRad>"
      << "<tr_smcrVal species=\"Western_Hemlock\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Western_Redcedar\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Amabilis_Fir\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Subalpine_Fir\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Hybrid_Spruce\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Lodgepole_Pine\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Trembling_Aspen\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Black_Cottonwood\">10</tr_smcrVal>"
      << "<tr_smcrVal species=\"Paper_Birch\">10</tr_smcrVal>"
      << "</tr_stdMaxCrownRad>"
      << "<tr_conversionDiam10ToDBH>"
      << "<tr_cdtdVal species=\"Western_Hemlock\">0.8008</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Western_Redcedar\">0.5944</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Amabilis_Fir\">0.7059</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Subalpine_Fir\">0.7776</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Hybrid_Spruce\">0.6933</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Lodgepole_Pine\">0.8014</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Trembling_Aspen\">0.7992</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Black_Cottonwood\">0.7926</tr_cdtdVal>"
      << "<tr_cdtdVal species=\"Paper_Birch\">0.7803</tr_cdtdVal>"
      << "</tr_conversionDiam10ToDBH>"
      << "<tr_interceptDiam10ToDBH>"
      << "<tr_idtdVal species=\"Western_Hemlock\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Western_Redcedar\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Amabilis_Fir\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Subalpine_Fir\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Hybrid_Spruce\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Lodgepole_Pine\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Trembling_Aspen\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Black_Cottonwood\">0</tr_idtdVal>"
      << "<tr_idtdVal species=\"Paper_Birch\">0</tr_idtdVal>"
      << "</tr_interceptDiam10ToDBH>"
      << "<tr_stdAsympCrownHt>"
      << "<tr_sachVal species=\"Western_Hemlock\">0.389</tr_sachVal>"
      << "<tr_sachVal species=\"Western_Redcedar\">0.368</tr_sachVal>"
      << "<tr_sachVal species=\"Amabilis_Fir\">0.464</tr_sachVal>"
      << "<tr_sachVal species=\"Subalpine_Fir\">0.454</tr_sachVal>"
      << "<tr_sachVal species=\"Hybrid_Spruce\">0.405</tr_sachVal>"
      << "<tr_sachVal species=\"Lodgepole_Pine\">0.201</tr_sachVal>"
      << "<tr_sachVal species=\"Trembling_Aspen\">0.301</tr_sachVal>"
      << "<tr_sachVal species=\"Black_Cottonwood\">0.42</tr_sachVal>"
      << "<tr_sachVal species=\"Paper_Birch\">0.315</tr_sachVal>"
      << "</tr_stdAsympCrownHt>"
      << "<tr_stdCrownHtExp>"
      << "<tr_scheVal species=\"Western_Hemlock\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Western_Redcedar\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Amabilis_Fir\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Subalpine_Fir\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Hybrid_Spruce\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Lodgepole_Pine\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Trembling_Aspen\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Black_Cottonwood\">1.0</tr_scheVal>"
      << "<tr_scheVal species=\"Paper_Birch\">1.0</tr_scheVal>"
      << "</tr_stdCrownHtExp>"
      << "<tr_slopeOfHeight-Diam10>"
      << "<tr_sohdVal species=\"Western_Hemlock\">0.03418</tr_sohdVal>"
      << "<tr_sohdVal species=\"Western_Redcedar\">0.0269</tr_sohdVal>"
      << "<tr_sohdVal species=\"Amabilis_Fir\">0.02871</tr_sohdVal>"
      << "<tr_sohdVal species=\"Subalpine_Fir\">0.02815</tr_sohdVal>"
      << "<tr_sohdVal species=\"Hybrid_Spruce\">0.02871</tr_sohdVal>"
      << "<tr_sohdVal species=\"Lodgepole_Pine\">0.03224</tr_sohdVal>"
      << "<tr_sohdVal species=\"Trembling_Aspen\">0.04796</tr_sohdVal>"
      << "<tr_sohdVal species=\"Black_Cottonwood\">0.04681</tr_sohdVal>"
      << "<tr_sohdVal species=\"Paper_Birch\">0.04101</tr_sohdVal>"
      << "</tr_slopeOfHeight-Diam10>"
      << "<tr_slopeOfAsymHeight>"
      << "<tr_soahVal species=\"Western_Hemlock\">0.0299</tr_soahVal>"
      << "<tr_soahVal species=\"Western_Redcedar\">0.0241</tr_soahVal>"
      << "<tr_soahVal species=\"Amabilis_Fir\">0.0263</tr_soahVal>"
      << "<tr_soahVal species=\"Subalpine_Fir\">0.0264</tr_soahVal>"
      << "<tr_soahVal species=\"Hybrid_Spruce\">0.0264</tr_soahVal>"
      << "<tr_soahVal species=\"Lodgepole_Pine\">0.0333</tr_soahVal>"
      << "<tr_soahVal species=\"Trembling_Aspen\">0.0352</tr_soahVal>"
      << "<tr_soahVal species=\"Black_Cottonwood\">0.0347</tr_soahVal>"
      << "<tr_soahVal species=\"Paper_Birch\">0.0454</tr_soahVal>"
      << "</tr_slopeOfAsymHeight>"
      << "<tr_whatSeedlingHeightDiam>"
      << "<tr_wsehdVal species=\"Western_Hemlock\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Western_Redcedar\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Amabilis_Fir\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Subalpine_Fir\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Hybrid_Spruce\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Lodgepole_Pine\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Trembling_Aspen\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Black_Cottonwood\">0</tr_wsehdVal>"
      << "<tr_wsehdVal species=\"Paper_Birch\">0</tr_wsehdVal>"
      << "</tr_whatSeedlingHeightDiam>"
      << "<tr_whatSaplingHeightDiam>"
      << "<tr_wsahdVal species=\"Western_Hemlock\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Western_Redcedar\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Amabilis_Fir\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Subalpine_Fir\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Hybrid_Spruce\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Lodgepole_Pine\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Trembling_Aspen\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Black_Cottonwood\">0</tr_wsahdVal>"
      << "<tr_wsahdVal species=\"Paper_Birch\">0</tr_wsahdVal>"
      << "</tr_whatSaplingHeightDiam>"
      << "<tr_whatAdultHeightDiam>"
      << "<tr_wahdVal species=\"Western_Hemlock\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Western_Redcedar\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Amabilis_Fir\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Subalpine_Fir\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Hybrid_Spruce\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Lodgepole_Pine\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Trembling_Aspen\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Black_Cottonwood\">0</tr_wahdVal>"
      << "<tr_wahdVal species=\"Paper_Birch\">0</tr_wahdVal>"
      << "</tr_whatAdultHeightDiam>"
      << "<tr_whatAdultCrownRadDiam>"
      << "<tr_wacrdVal species=\"Western_Hemlock\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Western_Redcedar\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Amabilis_Fir\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Subalpine_Fir\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Hybrid_Spruce\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Lodgepole_Pine\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Trembling_Aspen\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Black_Cottonwood\">0</tr_wacrdVal>"
      << "<tr_wacrdVal species=\"Paper_Birch\">0</tr_wacrdVal>"
      << "</tr_whatAdultCrownRadDiam>"
      << "<tr_whatAdultCrownHeightHeight>"
      << "<tr_wachhVal species=\"Western_Hemlock\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Western_Redcedar\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Amabilis_Fir\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Subalpine_Fir\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Hybrid_Spruce\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Lodgepole_Pine\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Trembling_Aspen\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Black_Cottonwood\">0</tr_wachhVal>"
      << "<tr_wachhVal species=\"Paper_Birch\">0</tr_wachhVal>"
      << "</tr_whatAdultCrownHeightHeight>"
      << "<tr_whatSaplingCrownRadDiam>"
      << "<tr_wscrdVal species=\"Western_Hemlock\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Western_Redcedar\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Amabilis_Fir\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Subalpine_Fir\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Hybrid_Spruce\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Lodgepole_Pine\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Trembling_Aspen\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Black_Cottonwood\">0</tr_wscrdVal>"
      << "<tr_wscrdVal species=\"Paper_Birch\">0</tr_wscrdVal>"
      << "</tr_whatSaplingCrownRadDiam>"
      << "<tr_whatSaplingCrownHeightHeight>"
      << "<tr_wschhVal species=\"Western_Hemlock\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Western_Redcedar\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Amabilis_Fir\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Subalpine_Fir\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Hybrid_Spruce\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Lodgepole_Pine\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Trembling_Aspen\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Black_Cottonwood\">0</tr_wschhVal>"
      << "<tr_wschhVal species=\"Paper_Birch\">0</tr_wschhVal>"
      << "</tr_whatSaplingCrownHeightHeight>"
      << "</allometry>";
}
